blank_issues_enabled: false
contact_links:
  - name: Questions and Answers
    url: https://github.com/numToStr/Comment.nvim/discussions
    about: Please ask (and/or answer) installation and usage questions in our discussions forum
